# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
<<<<<<< HEAD
  
=======
 
>>>>>>> 99182bdc55f0c71247860f3142ce87cd373a079c

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup Node.js Environment
      uses: actions/setup-node@v2-beta
      with:
        version:  12

<<<<<<< HEAD
    # Runs a set of commands using the runners shell
=======
    # Runs a set of commands using the runners shell- name: GitHub Action for Yarn
>>>>>>> 99182bdc55f0c71247860f3142ce87cd373a079c
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.1.0
      with:
       cmd: install
        
    - name: Creating build
      run : yarn build
     
    - name: Installing surge
      run : npm install -g surge
     
     
    - name: Deploying on surge 
<<<<<<< HEAD
      run : surge ./build http://expnse-tracker-app-inam.surge.sh/ --token ${{ secrets.SURGE_TOKEN }}
=======
      run : surge ./build http://covid-19-tracker-appinam.surge.sh/ --token ${{ secrets.SURGE_TOKEN }}
>>>>>>> 99182bdc55f0c71247860f3142ce87cd373a079c
